# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55736ae0a63f84db2a0e05d72bb5443751796d693ec9f75d3e8523245b2de89488cb961c826bb7fe6a123ce4c6b2ebd13fcac01b2a3fad1cfbbb6ff645fee709

test:
  secret_key_base: 75bee6615c1bce0f9647563a8a2ec8084c3396dff6873aa4efce67ef9d5996e1f50467908ed7d1f0eb9ede082dad5eff701cbda9a49be7599935d5e361985001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
